package clientparty;

import static clientparty.MenuPrincipal.DataBase;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 * @author Mateus
 */
public class MenuCadastro extends javax.swing.JFrame {
    private static String TIPO;
    private static String Cod;
    static ResultSet Resultados;
    
    
    /**
     * Creates new form MenuCadastro
     */
    //CONSTRUTOR DO MENU DE CADASTRO E CONSULTA/EDICAO
    public MenuCadastro(String tipo,String cod) {      
        Cod = cod;    
        toFront();
        try{
        TIPO = tipo;
        initComponents();
        setLocationRelativeTo(null);      
        if(TIPO.equals("CADASTRO_C")){
               TITULO.setText("CADASTRAR NOVO CLIENTE");
               LABEL1.setText("Nome:");
               LABEL2.setText("Endereço:");
               LABEL3.setText("Telefone:");
               LABEL4.setText("RG:");            
               CODE.setText("00"+Cod);
               LABEL5.setVisible(false);
               AREA5.setVisible(false);
        }
        if(TIPO.equals("CONSULTA_C")){
               TITULO.setText("CONSULTA E EDIÇÃO DE CLIENTE");
               LABEL1.setText("Nome:");
               LABEL2.setText("Endereço:");
               LABEL3.setText("Telefone:");
               LABEL4.setText("RG:");
               LABEL5.setVisible(false);
               AREA5.setVisible(false);
               CODE.setText(Cod);                    
               Resultados = DataBase.executeQuery("SELECT nome,endereco,telefone,rg FROM clientes WHERE codigo = '"+Cod+"'");
               while(Resultados.next()){
                   AREA1.setText(Resultados.getObject(1).toString());
                   AREA2.setText(Resultados.getObject(2).toString());
                   AREA3.setText(Resultados.getObject(3).toString());
                   AREA4.setText(Resultados.getObject(4).toString());
               }                                       
        }
        if(TIPO.equals("CADASTRO_D")){
               TITULO.setText("CADASTRAR NOVA DECORAÇÃO");
               LABEL1.setText("Tipo:");
               LABEL2.setText("Tema:");
               LABEL3.setText("Cores:");
               LABEL4.setText("Valor completa:");
               LABEL5.setText("N° peças:");
               CODE.setText("00"+Cod);
        }
        if(TIPO.equals("CONSULTA_D")){
               TITULO.setText("CONSULTA E EDIÇÃO DE DECORAÇÃO");
               LABEL1.setText("Tipo:");
               LABEL2.setText("Tema:");
               LABEL3.setText("Cores:");
               LABEL4.setText("Valor completa:");
               LABEL5.setText("N° peças:");
               CODE.setText(Cod);
               Resultados = DataBase.executeQuery("SELECT tipo,tema,cores,vcompleta,npecas FROM decoracoes WHERE codigo LIKE '"+Cod+"'  ");            
               while(Resultados.next()){
                   AREA1.setText(Resultados.getObject(1).toString());
                   AREA2.setText(Resultados.getObject(2).toString());
                   AREA3.setText(Resultados.getObject(3).toString());
                   AREA4.setText(Resultados.getObject(4).toString());
               }            
        }
        if(TIPO.equals("CADASTRO_M")){
               TITULO.setText("CADASTRAR NOVA MESA/CADEIRA");
               LABEL1.setText("Tipo:");
               LABEL2.setText("Marca:");
               LABEL3.setText("Modelo:");
               LABEL4.setText("Quantidade:");
               CODE.setText("00"+Cod);
               LABEL5.setVisible(false);
               AREA5.setVisible(false);
        }
        if(TIPO.equals("CONSULTA_M")){
               TITULO.setText("CONSULTA E EDIÇÃO DE MESA/CADEIRA");
               LABEL1.setText("Tipo:");
               LABEL2.setText("Marca:");
               LABEL3.setText("Modelo:");
               LABEL4.setText("Quantidade:");
               LABEL5.setVisible(false);
               AREA5.setVisible(false);
               CODE.setText(Cod);
               Resultados = DataBase.executeQuery("SELECT tipo,marca,modelo,quantidade FROM mesas WHERE codigo LIKE '"+Cod+"'  ");            
               while(Resultados.next()){
                   AREA1.setText(Resultados.getObject(1).toString());
                   AREA2.setText(Resultados.getObject(2).toString());
                   AREA3.setText(Resultados.getObject(3).toString());
                   AREA4.setText(Resultados.getObject(4).toString());
               }   
        }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Erro no cadastro, reinicie a aplicação!\n");
        }      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LABEL1 = new javax.swing.JLabel();
        CODE = new javax.swing.JTextField();
        LABEL2 = new javax.swing.JLabel();
        LABEL3 = new javax.swing.JLabel();
        LABEL4 = new javax.swing.JLabel();
        AREA1 = new javax.swing.JTextField();
        AREA2 = new javax.swing.JTextField();
        AREA3 = new javax.swing.JTextField();
        AREA4 = new javax.swing.JTextField();
        SALVAR = new javax.swing.JButton();
        LABEL5 = new javax.swing.JLabel();
        AREA5 = new javax.swing.JTextField();
        CANCELAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro/Edição");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        TITULO.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        TITULO.setForeground(new java.awt.Color(51, 51, 51));
        TITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TITULO.setText("NOVO CLIENTE");
        TITULO.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Codigo");

        LABEL1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LABEL1.setForeground(new java.awt.Color(51, 51, 51));
        LABEL1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LABEL1.setText("Info:");

        CODE.setEditable(false);
        CODE.setBackground(new java.awt.Color(255, 255, 255));
        CODE.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CODE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CODE.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        LABEL2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LABEL2.setForeground(new java.awt.Color(51, 51, 51));
        LABEL2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LABEL2.setText("Info:");

        LABEL3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LABEL3.setForeground(new java.awt.Color(51, 51, 51));
        LABEL3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LABEL3.setText("Info:");

        LABEL4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LABEL4.setForeground(new java.awt.Color(51, 51, 51));
        LABEL4.setText("Info:");

        SALVAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SALVAR.setForeground(new java.awt.Color(51, 51, 51));
        SALVAR.setText("Salvar");
        SALVAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SALVAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SALVARMouseClicked(evt);
            }
        });

        LABEL5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LABEL5.setForeground(new java.awt.Color(51, 51, 51));
        LABEL5.setText("Info:");

        CANCELAR.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        CANCELAR.setForeground(new java.awt.Color(51, 51, 51));
        CANCELAR.setText("Cancelar");
        CANCELAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CANCELAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)
                                .addComponent(CODE, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(LABEL5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AREA5))
                            .addComponent(LABEL1)
                            .addComponent(AREA1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABEL2)
                            .addComponent(AREA2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LABEL3)
                                .addGap(159, 159, 159)
                                .addComponent(LABEL4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AREA3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AREA4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(TITULO)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AREA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(LABEL5)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CODE, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(LABEL1)
                .addGap(6, 6, 6)
                .addComponent(AREA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LABEL2)
                        .addGap(6, 6, 6)
                        .addComponent(AREA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LABEL3)
                            .addComponent(LABEL4))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AREA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AREA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SALVAR)
                            .addComponent(CANCELAR))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALVARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALVARMouseClicked
        try{
               if(TIPO.equals("CADASTRO_C")){
                      DataBase.execute("INSERT INTO clientes (codigo,nome,endereco,telefone,rg) VALUES ('"+CODE.getText()+"','"+AREA1.getText()+"','"+AREA2.getText()+"','"+AREA3.getText()+"','"+AREA4.getText()+"')");;
               }
               if(TIPO.equals("CONSULTA_C")){
                      DataBase.execute("UPDATE clientes SET nome  = '"+AREA1.getText()+"', endereco = '"+AREA2.getText()+"', telefone = '"+AREA3.getText()+"', rg = '"+AREA4.getText()+"' WHERE codigo = '"+CODE.getText()+"'");                      
               }
               if(TIPO.equals("CADASTRO_D")){
                      DataBase.execute("INSERT INTO decoracoes (codigo,tipo,tema,cores,vcompleta,npecas) VALUES ('"+CODE.getText()+"','"+AREA1.getText()+"','"+AREA2.getText()+"','"+AREA3.getText()+"','"+AREA4.getText()+"','"+AREA5.getText()+"')");
               }
               if(TIPO.equals("CONSULTA_D")){
                      DataBase.execute("UPDATE decoracoes SET tipo  = '"+AREA1.getText()+"', tema = '"+AREA2.getText()+"', cores = '"+AREA3.getText()+"', vcompleta = '"+AREA4+"', npecas = '"+AREA5.getText()+"' WHERE codigo = '"+CODE.getText()+"'");
               }
               if(TIPO.equals("CADASTRO_M")){
                      DataBase.execute("INSERT INTO mesas (codigo,tipo,marca,modelo,quantidade) VALUES ('"+CODE.getText()+"','"+AREA1.getText()+"','"+AREA2.getText()+"','"+AREA3.getText()+"','"+AREA4.getText()+"')");
               }
               if(TIPO.equals("CONSULTA_M")){
                      DataBase.execute("UPDATE mesas SET tipo  = '"+AREA1.getText()+"', marca = '"+AREA2.getText()+"', modelo = '"+AREA3.getText()+"', quantidade = '"+AREA4.getText()+"' WHERE codigo = '"+CODE.getText()+"'");
               }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"ERRO NO BANCO DE DADOS, REINICIE A APLICACAO!"+e.getLocalizedMessage());
        }
        MenuPrincipal MENU = new MenuPrincipal();
        MENU.show();
        dispose();        
    }//GEN-LAST:event_SALVARMouseClicked

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        MenuPrincipal MENU = new MenuPrincipal();
        MENU.show();
        dispose();
    }//GEN-LAST:event_CANCELARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCadastro(TIPO,Cod).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AREA1;
    private javax.swing.JTextField AREA2;
    private javax.swing.JTextField AREA3;
    private javax.swing.JTextField AREA4;
    private javax.swing.JTextField AREA5;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JTextField CODE;
    private javax.swing.JLabel LABEL1;
    private javax.swing.JLabel LABEL2;
    private javax.swing.JLabel LABEL3;
    private javax.swing.JLabel LABEL4;
    private javax.swing.JLabel LABEL5;
    private javax.swing.JButton SALVAR;
    private javax.swing.JLabel TITULO;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}